### PR TITLE
Update on boarding slides

### PR DESCRIPTION
**Pull request by georgf**
* Update documentation links
* Kill most FHR and “unified” references (no need to explain the old FHR system anymore)
* Update Histograms.json example with new required fields & format
* Move Privacy & Data Collection policy changes to the front (seems good to start out with that to set the tone)
* Added contact information slide (teams, IRC, mailing list)
* Updated build flags (MOZILLA_OFFICIAL is not needed anymore, it just controls ping sending now)
* Add example graph for mean vs. median vs. geometric mean
* Merge Privacy policy & data collection review into one section (they go together anyway)

### CODE REVIEW

**Comment by vitillo** [comment]
What's the "Before we start" slide?

**Comment by vitillo** [comment]
Data collection policy mentions Telemetry probes before introducing what Telemetry is, that's confusing.

**Comment by georgf** [comment]
Before we start -> lets launch our cluster so it has some time to spin up. I saw it needs a few minutes.

Could be changed to use different terms, but i don't think this needs details at that point.

If you like the other changes, happy to change something back here if you have preferences (or you update it when needed?).

**Comment by vitillo** [comment]
Oh I see, that makes sense, you should add the "data engineering" team (my team) to the last slide as well. Besides the Data collection policy I am OK with all the changes.

**Comment by vitillo** [comment]
Any chance you could get a higher resolution plot of that geometric mean, median & mean comparison slide?

**Comment by vitillo** [comment]
Looks good, thanks.

**Pull request merged**
