### PR TITLE
Convert from .key to new-mozilla-style .pptx.

### PR DESCRIPTION
**Pull request by chutten**
Also, add a slide for talking about sql.t.m.o

### CODE REVIEW

**Comment by vitillo** [comment]
The slides look generally good, thanks for doing this. I think there is still a small effort needed to make them prettier (though that's subjective). 

Slide *: why is there a "public" banner on the bottom left?
Slide *: can we have all the links at the bottom of the slides with the same font size?
Slide 7: the link is crammed in there, let's just put it in the reference section
Slide 8: let's remove any mention of FHR
Slide 9: there is no mention of `MOZILLA_OFFICIAL`, why?
Slide 10 (and others): when you add a screenshot is there anyway you could make it a bit more pleasant to the eye, like adding some shaded borders or something like in the original set of slides?
Slide 43: Please add back the flags required for testing unless it'd documented somewhere else on a wiki

**Comment by chutten** [comment]
* the public notation is to make it adhere to the mozilla slide style. public/confidential/insiders only, etc.
* I was trying to keep them as big as possible while still fitting on a single line. I can standardize on the smallest size.
* It's already in references. I'll omit it from the slide
* It's called FHR in the preferences and it comes up again when talking about data lag in metrics.services.m.c data (and data lag in general). I'd like to keep it for now.
* MOZILLA_OFFICIAL is to enable data upload. We don't want to enable data upload for the build... _oh_ you mean informationally-speaking? Yeah, I can put that in: "To actually send data, and not just collect and store it, you'll also need MOZILLA_OFFICIAL=1"
* Drop shadows aren't currently natively supported by Google Slides, but I can throw rectangles in.
* I'll add the flags slide back in.

**Comment by chutten** [comment]
I didn't end up standardizing the link size, since they vary so much in width. Instead, I ensured that the bottom-of-slide link sizes were standard within sections. It seems to work.

I added borders to the screenshots, except the green jellybean xkcd I had to chop up, as it would look hideous.

**Comment by chutten** [comment]
Fixed content issue. Extended collection is opt-in on _all_ of release.

**Comment by vitillo** [comment]
r+

**Pull request merged**
